### ISSUE TITLE
Remove Dependence on Old Files

### ISSUE THREAD

**Issue by caleb-james-smith** [susy2015/ZInvisible#191]
Right now the following files are needed to run makePlots.... but we should remove this dependence as I don't think these files are needed.

```
2019-05-10 14:44:14.437187: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
Error in <TFile::TFile>: file effhists_GJets.root does not exist
Error in <TFile::TFile>: file dataMCreweight.root does not exist
Error in <TFile::TFile>: file dataMCreweight_allJets.root does not exist

binEra_ : SB_v1_2017


binEra_ : SB_v1_2017

Error in <TFile::TFile>: file allINone_bTagEff.root does not exist
Could not find n_eff_b_TTbarSingleLepT in Btag file. Will use TTbarSingleLepT as default
```

**Comment by caleb-james-smith** [comment]
More details.
```
#6  0x000000000068fd2c in BTagCorrectorTemplate<float>::SetEffs (this=0x9dfe930, file=0x9be6460, suffix=...) at /uscms_data/d3/ahenckel/TTZ/CMSSW_10_2_9/src/SusyAnaTools/Tools/BTagCorrector.h:86
#7  0x0000000000685d10 in BTagCorrectorTemplate<float>::BTagCorrectorTemplate (this=0x9dfe930, file=..., CSVFilePath=..., CSVFile=..., isFastSim=false, suffix=...) at /uscms_data/d3/ahenckel/TTZ/CMSSW_10_2_9/src/SusyAnaTools/Tools/BTagCorrector.h:39
#8  0x000000000067f9b5 in BTagCorrector::BTagCorrector (this=0x9dfe930, file=..., CSVFilePath=..., isFastSim=false, suffix=...) at /uscms_data/d3/ahenckel/TTZ/CMSSW_10_2_9/src/SusyAnaTools/Tools/BTagCorrector.h:522
#9  0x0000000000662c54 in RegisterFunctionsNTuple::RegisterFunctionsNTuple (this=0x25dbc60, isCondor=false, sbEra=...) at RegisterFunctions.cc:152
#10 0x0000000000611388 in main (argc=8, argv=0x7ffcbcacb1e8) at MakePlots.C:1922
```

**Comment by caleb-james-smith** [comment]
another file
```PileupHistograms_0121_69p2mb_pm4p6.root```
