### ISSUE TITLE
Fix pdf systematic for CR.

### ISSUE THREAD

**Issue by caleb-james-smith** [susy2015/ZInvisible#303]
The pdf systematic is not working in the photon CR.
Error is likely due to pdf syst. not done for metWithPhoton.

```
getCRUnitMap(): variable = nCRUnitLowDM_drPhotonCleaned_jetpt30
getSimpleMap(): variableWithTag = nCRUnitLowDM_drPhotonCleaned_jetpt30
getCRUnitMap(): variable = nCRUnitHighDM_drPhotonCleaned_jetpt30
getSimpleMap(): variableWithTag = nCRUnitHighDM_drPhotonCleaned_jetpt30
ERROR: unable to load histogram metWithPhoton/DataMC_Photon_LowDM_met_NBge2_NJge7_pdf_syst_up_jetpt30metWithPhotonmetWithPhotonQCDstack
Traceback (most recent call last):
  File "python/run_systematics.py", line 770, in <module>
    main()
  File "python/run_systematics.py", line 766, in main
    run(era, eras, runs_json, syst_json, verbose)
  File "python/run_systematics.py", line 640, in run
    S.getShape(         result_file,  era, systTag, varTag)
  File "/uscms_data/d3/caleb/SusyAnalysis/CMSSW_10_2_9/src/ZInvisible/Tools/python/shape_photon_met.py", line 223, in getShape
    h_mc = h_GJets.Clone("h_mc")
ReferenceError: attempt to access a null-pointer
```

**Comment by caleb-james-smith** [comment]
Fix in this PR: https://github.com/susy2015/ZInvisible/pull/304
